use clap::CommandFactory;
use clap_mangen::Man;
use std::io::Write;
use std::path::PathBuf;

// Reuse the same CLI definition the binary uses. `build.rs` is compiled before
// the `dfm` lib, so this module is copied in by path rather than imported.
#[path = "src/cli.rs"]
mod cli;

// Converts the root README.md (the project's documentation of record) into the
// prose man-page sections. Kept separate so `build.rs` stays short.
#[path = "build/man.rs"]
mod man;

// The apostrophe preamble defines `\*(Aq` and is emitted once, at the very top
// of the page. The sections generated by `clap_mangen` embed it too, so each is
// stripped before it is copied into the final output.
const APOSTROPHE_PREAMBLE: &str = ".ie \\n(.g .ds Aq \\(aq\n.el .ds Aq '\n";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build/man.rs");
    println!("cargo:rerun-if-changed=src/cli.rs");
    println!("cargo:rerun-if-changed=README.md");

    let manifest_dir = PathBuf::from(env("CARGO_MANIFEST_DIR"));
    let readme = std::fs::read_to_string(manifest_dir.join("README.md"))
        .unwrap_or_else(|error| panic!("cannot read README.md: {error}"));

    // Write `dfm.1` next to the built binary: `<target>/<profile>/dfm.1`.
    // `[package.metadata.aur] files` points at `target/release/dfm.1` so `cargo
    // aur` packs it into the release tarball and installs it to
    // `/usr/share/man/man1/dfm.1`. Writing into the target dir keeps the repo
    // root clean. `OUT_DIR` is `<target>/<profile>/build/<pkg>-<hash>/out`.
    let out_dir = PathBuf::from(env("OUT_DIR"));
    let profile = out_dir
        .ancestors()
        .nth(3)
        .expect("no profile dir above OUT_DIR");
    let target_root = out_dir
        .ancestors()
        .nth(4)
        .expect("no target dir above OUT_DIR");
    let out_path = target_root.join(profile).join("dfm.1");
    let mut out = std::io::BufWriter::new(std::fs::File::create(&out_path).unwrap());

    let man = Man::new(cli::Args::command());

    out.write_all(APOSTROPHE_PREAMBLE.as_bytes()).unwrap();
    write_man_section(&mut out, &man, Man::render_title);
    write_man_section(&mut out, &man, Man::render_name_section);
    write_man_section(&mut out, &man, Man::render_synopsis_section);

    out.write_all(b".SH DESCRIPTION\n").unwrap();
    out.write_all(man::description(&readme).as_bytes()).unwrap();

    write_man_section(&mut out, &man, Man::render_options_section);

    out.write_all(man::body(&readme).as_bytes()).unwrap();

    write_man_section(&mut out, &man, Man::render_version_section);

    out.flush().unwrap();
}

fn write_man_section(
    writer: &mut dyn Write,
    man: &Man,
    render: fn(&Man, &mut dyn Write) -> std::io::Result<()>,
) {
    let mut buffer = Vec::new();
    render(man, &mut buffer).unwrap();
    let rendered = std::str::from_utf8(&buffer).unwrap();
    let without_preamble = rendered
        .strip_prefix(APOSTROPHE_PREAMBLE)
        .unwrap_or(rendered);
    writer.write_all(without_preamble.as_bytes()).unwrap();
}

fn env(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| panic!("build env var {name} missing"))
}
