#!/usr/bin/bash

set -euP

TRACE=""
while [ $# -gt 0 ]; do
    case "$1" in
        -x) TRACE="-x"; shift ;;
        --) shift; break ;;
        *) break ;;
    esac
done

if ! ( whatis 7z > /dev/null; exit $? ); then
    echo ERROR 7z archiver is not available on PATH
fi

TEST_FILE_TO_RUN="${1:-}"

PROGRAMM_NAME_IN_SHELL="dfm"
EXECUTABLE_NAME="dfm"

TESTS_DIR=`readlink -f "$(dirname "$0")"`
PROJECT_ROOT=$(readlink -f "$TESTS_DIR/../")
DEBUG_EXECUTABLE="$PROJECT_ROOT/target/debug/$EXECUTABLE_NAME"
RELEASE_EXECUTABLE="$PROJECT_ROOT/target/release/$EXECUTABLE_NAME"

EXECUTABLE=
if [[ -f "$DEBUG_EXECUTABLE" ]]; then
    EXECUTABLE="$DEBUG_EXECUTABLE"
elif [[ -f "$RELEASE_EXECUTABLE" ]]; then
    EXECUTABLE="$RELEASE_EXECUTABLE"
else
    echo "project is not built"
    exit 1
fi
export EXECUTABLE

eval 'function '$PROGRAMM_NAME_IN_SHELL'() { "$EXECUTABLE" "$@" && sleep 0.01s; }'
export "$PROGRAMM_NAME_IN_SHELL"

function write() {
    echo "$1" > "$2" && sleep 0.01s
}
export write;

function assert() {
    if ! test "$@"; then
        echo "Assertion failed"
        exit 1
    fi
}
export assert

function assert_fail() {
    if "$@"; then
        echo "Assertion failed"
        exit 1
    fi
}
export assert_fail

# mktemp creates directory in the /tmp wich is mounted to memory filesystem
readonly TMP_HOME=$(mktemp -d)
trap 'rm -rf -- "$TMP_HOME"' EXIT

TEST_FILE_TO_RUN_ABS=
if [ -n "$TEST_FILE_TO_RUN" ]; then
  TEST_FILE_TO_RUN_ABS=$(readlink -f "$TEST_FILE_TO_RUN")
fi

export HOME="$TMP_HOME"
cd $HOME

TEST_CASES=$(find "$TESTS_DIR" -type f -name 'test*.sh' -printf "%p\n")
TEST_COUNT=$(echo "$TEST_CASES" | wc -l)
if [ -n "$TEST_FILE_TO_RUN_ABS" ]; then
    echo "running 1 test (of $TEST_COUNT)"
else
    echo "running $TEST_COUNT tests"
fi

SUCCED_COUNTER=0
FAILED_COUNTER=0

if [ -n "$TEST_FILE_TO_RUN_ABS" ]; then
    test_name="$(basename $TEST_FILE_TO_RUN_ABS)"
    if ( set -eEu $TRACE; source "$TEST_FILE_TO_RUN_ABS" ) ; then
        echo "---- $test_name ✅"
        SUCCED_COUNTER=$((SUCCED_COUNTER + 1))
    else
        echo "---- $test_name ❌"
        FAILED_COUNTER=$((FAILED_COUNTER + 1))
    fi
else
    for test_case in $TEST_CASES; do
        test_name="$(basename $test_case)"

        # launch test
        if ( set -eEu $TRACE; source "$test_case" ) ; then
            echo "---- $test_name ✅"
            SUCCED_COUNTER=$((SUCCED_COUNTER + 1))
        else
            echo "---- $test_name ❌"
            FAILED_COUNTER=$((FAILED_COUNTER + 1))
        fi

        # remove all garbade generated by the test
        find "$TMP_HOME" -mindepth 1 -exec rm -rf {} \; 2>/dev/null || true
    done;
fi

echo "succed $SUCCED_COUNTER"
echo "failed $FAILED_COUNTER"

test $FAILED_COUNTER -eq 0
exit $?
